package auth

// ExternalAccount describes an association between user account on AdapterIS and another on a different website.
type ExternalAccount struct {
	//Id is just an autogenerated unique identifier of this association allowing for 1:M association of our user to external.
	Id         int
	//UserId is an id of user account on AdapterIS
	UserId     int
	//ExternalId is an id of a user account on a different website. May possibly be user's email, login or just a numeric value.
	ExternalId string
}

type ExternalAccountRepository interface {
	ReadAll() ([]ExternalAccount, error)
}
