package auth

import (
	"context"
	"time"
)

// ExternalAccount describes an association between user account on AdapterIS and another on a different website.
type ExternalAccount struct {
	//ID is just an autogenerated unique identifier of this association allowing for 1:M association of our user to external.
	ID int
	//UserId is an id of user account on AdapterIS
	UserId int
	//ExternalId is an id of a user account on a different website. May possibly be user's email, login or just a numeric value.
	ExternalId string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ExternalAccountStorage interface {
	FindAll(ctx context.Context) ([]ExternalAccount, error)
	FindByExternalId(ctx context.Context, id string) (ExternalAccount, error)
}
